# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RunLoop' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RunLoop
  pod 'AFNetworking', '~> 3.1.0'

  target 'RunLoopTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RunLoopUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
