# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SwiftApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'AFNetworking', '~> 3.1.0'
  pod 'MJRefresh', '~> 3.1.12'
  pod 'MBProgressHUD', '~> 1.0.0'
  pod 'APNumberPad', '~> 1.1.3'
  pod 'Bugrpt', '~> 1.2.2'
  pod 'GTSDK', '~> 1.6.2.0'
  pod 'SDWebImage', '~> 4.0.0'
  pod 'OpenShare', '~> 0.0.1'
  pod 'SVProgressHUD', '~> 2.1.2'
  pod 'SDWebImage/GIF'   #SDWebImage4.0以后的版本gif依赖了FLAnimatedImage
  # Pods for SwiftApp

  target 'SwiftAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SwiftAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
