# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'JZCycleScrollView' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
pod 'SDWebImage', '~> 4.1.0'
  # Pods for JZCycleScrollView

  target 'JZCycleScrollViewTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'JZCycleScrollViewUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
